/*
 * This source file was generated by the Gradle 'init' task
 */
package org.drahun

fun main() {
    println(evenOrOdd(4))
    println(evenOrOdd(7))

    println(multiplyByFourIfEvenOrByFiveIfOdd(4))
    println(multiplyByFourIfEvenOrByFiveIfOdd(7))

    println(returnNegative(5))
    println(returnNegative(-3))

    println(returnCentury(1905))
    println(returnCentury(1700))

    println(min(listOf(3, 1, 4, 1, 5, 9)))
    println(min(listOf(-2, -3, -1, -5, -4)))

    println(twoMax(listOf(3, 1, 4, 1, 5, 9)))
    println(twoMax(listOf(-2, -3, -1, -5, -4)))

    println(positiveCountAndNegativeSum(listOf(1, -2, 3, -4, 5)))
    println(positiveCountAndNegativeSum(listOf(-1, -2, -3, -4, -5)))
    println(positiveCountAndNegativeSum(emptyList()))

    println(numberOfVowels("Hello, World!"))
    println(numberOfVowels("Kotlin Programming"))

    println(returnMiddleCharacter("Hello"))
    println(returnMiddleCharacter("Kotlin"))

    println(multiplyTable(3))
    println(multiplyTable(5))
}

fun evenOrOdd(number: Int): String {
    return if (number % 2 == 0) "Even" else "Odd"
}

fun multiplyByFourIfEvenOrByFiveIfOdd(number: Int): Int {
    return if (number % 2 == 0) number * 4 else number * 5
}

fun returnNegative(number: Int): Int {
    return if (number > 0) -number else number
}

fun returnCentury(year: Int): Int {
    val century = (year - 1) / 100 + 1
    return century
}

fun min(array: List<Int>): Int {
    var min = array[0]
    
    for (i in 1 until array.size) {
        if (array[i] < min) {
            min = array[i]
        }
    }

    return min
}

fun twoMax(array: List<Int>): List<Int> {
    var max1 = Int.MIN_VALUE
    var max2 = Int.MIN_VALUE

    for (number in array) {
        if (number > max1) {
            max2 = max1
            max1 = number
        } else if (number > max2) {
            max2 = number
        }
    }

    return listOf(max1, max2)
}

fun positiveCountAndNegativeSum(array: List<Int>?): List<Int> {

    if (array == null || array.isEmpty()) {
        return listOf();
    }

    var positiveCount = 0
    var negativeSum = 0

    for (number in array) {
        if (number > 0) {
            positiveCount++
        } else if (number < 0) {
            negativeSum += number
        }
    }

    return listOf(positiveCount, negativeSum)
}

fun numberOfVowels(string: String): Int {
    val vowels = "aeiouy"
    var count = 0

    for (char in string) {
        if (vowels.contains(char.lowercase())) {
            count++
        }
    }

    return count
}

fun returnMiddleCharacter(string: String): String {
    if (string.length % 2 == 0) {
        return string.substring(string.length / 2 - 1, string.length / 2 + 1)
    }
    return string.substring(string.length / 2, string.length / 2 + 1)
}

fun multiplyTable(number: Int): List<List<Int>> {
    val table = mutableListOf<List<Int>>()

    for (i in 1..number) {
        val row = mutableListOf<Int>()
        for (j in 1..number) {
            row.add(i * j)
        }
        table.add(row)
    }
    return table
}