/*
 * This source file was generated by the Gradle 'init' task
 */
package org.drahun

interface Queue<T : Any> {
    fun enqueue(element: T): Boolean
    fun dequeue(): T?
    val count: Int
        get
    val isEmpty: Boolean
        get() = count == 0
    fun peek(): T?
}

class ArrayListQueue<T : Any> : Queue<T> {
    private val list = ArrayList<T>()

    override fun enqueue(element: T): Boolean {
        list.add(element)
        return true
    }

    override fun dequeue(): T? {
        return if (isEmpty) null else list.removeAt(0)
    }

    override val count: Int
        get() = list.size

    override fun peek(): T? {
        return list.firstOrNull()
    }

    override fun toString(): String = list.toString()
}

fun main() {
    val queue = ArrayListQueue<String>()

    println("=== Черга на основі ArrayList ===\n")

    println("enqueue(\"Ray\")   -> ${queue.enqueue("Ray")}")
    println("enqueue(\"Brian\") -> ${queue.enqueue("Brian")}")
    println("enqueue(\"Eric\")  -> ${queue.enqueue("Eric")}")
    println("\nЧерга: $queue")
    println("count: ${queue.count}")
    println("isEmpty: ${queue.isEmpty}")

    println("\npeek() -> ${queue.peek()}")
    println("Черга після peek: $queue")

    println("\ndequeue() -> ${queue.dequeue()}")
    println("dequeue() -> ${queue.dequeue()}")
    println("Черга: $queue")
    println("count: ${queue.count}")

    println("\ndequeue() -> ${queue.dequeue()}")
    println("isEmpty: ${queue.isEmpty}")

    println("dequeue() з порожньої -> ${queue.dequeue()}")
    println("peek() з порожньої    -> ${queue.peek()}")
}