/*
 * This source file was generated by the Gradle 'init' task
 */
package org.drahun

internal class ConsoleInputWrapper {
    companion object {
        fun readString(prompt: String? = null, validator: ((String) -> Boolean)? = null): String {
            if (prompt != null) println(prompt)
            while (true) {
                print("> ")
                val input = readlnOrNull()?.trim()
                if (input.isNullOrBlank()) { println("Invalid input"); continue }
                if (validator?.invoke(input) == false) { println("Invalid input"); continue }
                return input
            }
        }

        fun readInt(prompt: String? = null, validator: ((Int) -> Boolean)? = null): Int {
            while (true) {
                val input = readString(prompt)
                val number = input.toIntOrNull()
                if (number == null) { println("Invalid number"); continue }
                if (validator?.invoke(number) == false) { println("Invalid number"); continue }
                return number
            }
        }
    }
}

data class CoffeeRecipe(val name: String, val water: Int, val milk: Int, val beans: Int, val price: Int)

class CoffeeMachine(
    private var water: Int = 400,
    private var milk: Int = 540,
    private var beans: Int = 120,
    private var cups: Int = 9,
    private var money: Int = 550
) {
    private val recipes = mapOf(
        "1" to CoffeeRecipe("espresso",   250,   0, 16, 4),
        "2" to CoffeeRecipe("latte",      350,  75, 20, 7),
        "3" to CoffeeRecipe("cappuccino", 200, 100, 12, 6)
    )

    fun getStatus(): String = """
        The coffee machine has:
        $water of water
        $milk of milk
        $beans of coffee beans
        $cups of disposable cups
        $money of money
    """.trimIndent()

    fun buy(choice: String): String {
        if (choice == "back") return ""
        val recipe = recipes[choice] ?: return "Unknown coffee type."
        val shortage = checkIngredients(recipe) ?: run {
            water -= recipe.water
            milk  -= recipe.milk
            beans -= recipe.beans
            cups  -= 1
            money += recipe.price
            return "I have enough resources, making you a coffee!"
        }
        return "Sorry, not enough $shortage!"
    }

    fun fill(addWater: Int, addMilk: Int, addBeans: Int, addCups: Int) {
        water += addWater
        milk  += addMilk
        beans += addBeans
        cups  += addCups
    }

    fun take(): Int = money.also { money = 0 }

    private fun checkIngredients(recipe: CoffeeRecipe): String? = when {
        water < recipe.water -> "water"
        milk  < recipe.milk  -> "milk"
        beans < recipe.beans -> "coffee beans"
        cups  < 1            -> "disposable cups"
        else                 -> null
    }
}

val actions: Map<String, (CoffeeMachine) -> Unit> = mapOf(
    "remaining" to { m ->
        println(m.getStatus())
    },
    "buy" to { m ->
        val choice = ConsoleInputWrapper.readString(
            prompt = "What do you want to buy? 1 - espresso, 2 - latte, 3 - cappuccino, back – to main menu:",
            validator = { it in listOf("1", "2", "3", "back") }
        )
        val result = m.buy(choice)
        if (result.isNotEmpty()) println(result)
    },
    "fill" to { m ->
        m.fill(
            ConsoleInputWrapper.readInt("Write how many ml of water do you want to add:",     { it >= 0 }),
            ConsoleInputWrapper.readInt("Write how many ml of milk do you want to add:",      { it >= 0 }),
            ConsoleInputWrapper.readInt("Write how many grams of coffee beans do you want to add:", { it >= 0 }),
            ConsoleInputWrapper.readInt("Write how many disposable cups of coffee do you want to add:", { it >= 0 })
        )
    },
    "take" to { m ->
        println("I gave you ${m.take()}")
    }
)

private val validActions = setOf("buy", "fill", "take", "remaining", "exit")

fun main() {
    val machine = CoffeeMachine()
    while (true) {
        val action = ConsoleInputWrapper.readString(
            prompt = "Write action (buy, fill, take, remaining, exit):",
            validator = { it in validActions }
        )
        if (action == "exit") break
        actions[action]?.invoke(machine)
    }
}