/*
 * This source file was generated by the Gradle 'init' task
 */


package org.drahun

import java.awt.*
import javax.swing.*

fun main() {
    val model = CoffeeMachineModel()

    // val view: View = ConsoleView()

    val view: View = SwingView()

    val controller = Controller(model, view)
    
    controller.initApplication()
}

enum class CoffeeType(val water: Int, val milk: Int, val beans: Int, val cups: Int, val price: Int) {
    ESPRESSO(250, 0, 16, 1, 4),
    LATTE(350, 75, 20, 1, 7),
    CAPPUCCINO(200, 100, 12, 1, 6)
}

data class Resources(
    val water: Int = 0,
    val milk: Int = 0,
    val beans: Int = 0,
    val cups: Int = 0,
    val money: Int = 0
)

data class Order(val type: CoffeeType)

data class Response(
    val isSuccess: Boolean,
    val message: String,
    val currentResources: Resources
)

class CoffeeMachineModel {
    private var state = Resources(water = 400, milk = 540, beans = 120, cups = 9, money = 550)

    fun processOrder(order: Order): Response {
        val recipe = order.type
        
        val missingResource = when {
            state.water < recipe.water -> "воду"
            state.milk < recipe.milk -> "молоко"
            state.beans < recipe.beans -> "кавові зерна"
            state.cups < recipe.cups -> "одноразові стаканчики"
            else -> null
        }

        if (missingResource != null) {
            return Response(false, "Вибачте, не вистачає: $missingResource!", state)
        }

        state = Resources(
            water = state.water - recipe.water,
            milk = state.milk - recipe.milk,
            beans = state.beans - recipe.beans,
            cups = state.cups - recipe.cups,
            money = state.money + recipe.price
        )
        return Response(true, "Матеріалів достатньо. Готую вашу каву...", state)
    }

    fun addResources(added: Resources): Response {
        state = Resources(
            water = state.water + added.water,
            milk = state.milk + added.milk,
            beans = state.beans + added.beans,
            cups = state.cups + added.cups,
            money = state.money
        )
        return Response(true, "Ресурси успішно поповнено!", state)
    }

    fun takeMoney(): Response {
        val takenAmount = state.money
        state = state.copy(money = 0)
        return Response(true, "Видано $takenAmount $", state)
    }

    fun getCurrentStatus(): Response {
        return Response(true, "Поточний стан ресурсів", state)
    }
}

interface View {
    fun setController(controller: Controller)
    fun displayResponse(response: Response)
    fun start()
}

class Controller(private val model: CoffeeMachineModel, private val view: View) {
    
    init {
        view.setController(this)
    }

    fun initApplication() {
        view.start()
        view.displayResponse(model.getCurrentStatus())
    }

    fun onBuyCoffee(type: CoffeeType) {
        val response = model.processOrder(Order(type))
        view.displayResponse(response)
    }

    fun onFillResources(resources: Resources) {
        val response = model.addResources(resources)
        view.displayResponse(response)
    }

    fun onTakeMoney() {
        val response = model.takeMoney()
        view.displayResponse(response)
    }
}


class ConsoleView : View {
    private lateinit var controller: Controller

    override fun setController(controller: Controller) {
        this.controller = controller
    }

    override fun displayResponse(response: Response) {
        println("\n=== ПОВІДОМЛЕННЯ: ${response.message} ===")
        val res = response.currentResources
        println("Поточні ресурси: Вода=${res.water}мл, Молоко=${res.milk}мл, Зерна=${res.beans}г, Стакани=${res.cups}шт, Гроші=${res.money}$")
    }

    override fun start() {
        println("Консольна кавомашина запущена.")
        while (true) {
            println("\nДія (buy, fill, take, exit):")
            when (readlnOrNull()?.trim()?.lowercase()) {
                "buy" -> handleBuy()
                "fill" -> handleFill()
                "take" -> controller.onTakeMoney()
                "exit" -> return
                else -> println("Невідома команда!")
            }
        }
    }

    private fun handleBuy() {
        println("Що купуємо? 1 - Еспресо, 2 - Лате, 3 - Капучино, back - Назад:")
        when (readlnOrNull()?.trim()) {
            "1" -> controller.onBuyCoffee(CoffeeType.ESPRESSO)
            "2" -> controller.onBuyCoffee(CoffeeType.LATTE)
            "3" -> controller.onBuyCoffee(CoffeeType.CAPPUCCINO)
            "back" -> return
            else -> println("Невірний вибір.")
        }
    }

    private fun handleFill() {
        println("Введіть кількість води (мл):")
        val water = readlnOrNull()?.toIntOrNull() ?: 0
        println("Введіть кількість молока (мл):")
        val milk = readlnOrNull()?.toIntOrNull() ?: 0
        println("Введіть кількість зерен (г):")
        val beans = readlnOrNull()?.toIntOrNull() ?: 0
        println("Введіть кількість стаканчиків:")
        val cups = readlnOrNull()?.toIntOrNull() ?: 0

        controller.onFillResources(Resources(water = water, milk = milk, beans = beans, cups = cups))
    }
}

class SwingView : View {
    private lateinit var controller: Controller

    private val frame = JFrame("Coffee Machine GUI")
    private val infoTextArea = JTextArea(6, 40)
    
    private val waterField = JTextField("0", 5)
    private val milkField = JTextField("0", 5)
    private val beansField = JTextField("0", 5)
    private val cupsField = JTextField("0", 5)

    override fun setController(controller: Controller) {
        this.controller = controller
    }

    override fun displayResponse(response: Response) {
        val res = response.currentResources
        val statusText = """
            Статус: ${response.message}
            
            В наявності:
            💧 Вода: ${res.water} мл
            🥛 Молоко: ${res.milk} мл
            ☕ Зерна: ${res.beans} г
            🥤 Стакани: ${res.cups} шт
            💵 Гроші: ${res.money} $
        """.trimIndent()
        
        infoTextArea.text = statusText
    }

    override fun start() {
        frame.defaultCloseOperation = JFrame.EXIT_ON_CLOSE
        frame.layout = BorderLayout(10, 10)

        // 1. Інформаційна панель (зверху)
        infoTextArea.isEditable = false
        infoTextArea.font = Font("Monospaced", Font.BOLD, 14)
        val infoPanel = JPanel().apply {
            border = BorderFactory.createTitledBorder("Інформаційна панель")
            add(JScrollPane(infoTextArea))
        }

        val orderPanel = JPanel(GridLayout(1, 3, 10, 10)).apply {
            border = BorderFactory.createTitledBorder("Замовлення кави")
            
            val btnEspresso = JButton("Еспресо").apply { addActionListener { controller.onBuyCoffee(CoffeeType.ESPRESSO) } }
            val btnLatte = JButton("Лате").apply { addActionListener { controller.onBuyCoffee(CoffeeType.LATTE) } }
            val btnCappuccino = JButton("Капучино").apply { addActionListener { controller.onBuyCoffee(CoffeeType.CAPPUCCINO) } }
            
            add(btnEspresso)
            add(btnLatte)
            add(btnCappuccino)
        }

        val actionPanel = JPanel(GridLayout(2, 1, 5, 5))

        val fillPanel = JPanel(FlowLayout()).apply {
            border = BorderFactory.createTitledBorder("Заповнення ресурсів")
            add(JLabel("Вода:"))
            add(waterField)
            add(JLabel("Молоко:"))
            add(milkField)
            add(JLabel("Зерна:"))
            add(beansField)
            add(JLabel("Стакани:"))
            add(cupsField)

            val btnFill = JButton("Заправити").apply {
                addActionListener {
                    val w = waterField.text.toIntOrNull() ?: 0
                    val m = milkField.text.toIntOrNull() ?: 0
                    val b = beansField.text.toIntOrNull() ?: 0
                    val c = cupsField.text.toIntOrNull() ?: 0
                    controller.onFillResources(Resources(water = w, milk = m, beans = b, cups = c))
                    
                    waterField.text = "0"; milkField.text = "0"; beansField.text = "0"; cupsField.text = "0"
                }
            }
            add(btnFill)
        }

        val takePanel = JPanel(FlowLayout()).apply {
            val btnTake = JButton("Зняти гроші").apply {
                background = Color(255, 100, 100)
                addActionListener { controller.onTakeMoney() }
            }
            add(btnTake)
        }

        actionPanel.add(fillPanel)
        actionPanel.add(takePanel)

        frame.add(infoPanel, BorderLayout.NORTH)
        frame.add(orderPanel, BorderLayout.CENTER)
        frame.add(actionPanel, BorderLayout.SOUTH)

        frame.pack()
        frame.setLocationRelativeTo(null)
        frame.isVisible = true
    }
}

