/*
 * This source file was generated by the Gradle 'init' task
 */
package org.drahun

public final class RockPaperScissors(private val gameEngine: GameEngine) {

    public fun play(player1: Player, player2: Player) {
        while (true) {

            println("Available moves:")

            for (i in gameEngine.moves.indices) {
                println("$i: ${gameEngine.moves[i]}")
            }

            println("Player 1, enter your move:")
            val player1Move = player1.getMove()

            println("Player 2, enter your move:")
            val player2Move = player2.getMove()

            val result = gameEngine.checkWinner(player1Move, player2Move)

            println("Player 1 chose: ${gameEngine.moves[player1Move]}")
            println("Player 2 chose: ${gameEngine.moves[player2Move]}")

            when (result) {
                GameResult.WIN -> println("Player 1 wins!")
                GameResult.LOSE -> println("Player 2 wins!")
                GameResult.DRAW -> println("It's a draw!")
            }

            println("Do you want to play again? (yes/no)")
            val playAgain = ConsoleInputWrapper.readString(validator = { it.equals("yes", ignoreCase = true) || it.equals("no", ignoreCase = true) })
            if (playAgain.equals("no", ignoreCase = true)) {
                println("Thanks for playing!")
                break
            }
        }
    }

}

public final class GameEngine(internal val moves: List<String>) {

    init {
        require(moves.size >= 3 && moves.size % 2 == 1) {
            "Number of moves must be an odd number greater than or equal to 3"
        }
    }

    public fun checkWinner(player1Move: Int, player2Move: Int): GameResult {
        if (player1Move == player2Move) return GameResult.DRAW
        
        val n = moves.size
        val half = n / 2
        
        val diff = (player2Move - player1Move + n) % n
        
        return if (diff <= half) GameResult.LOSE else GameResult.WIN
    }
    
}
public enum class GameResult {
    WIN,
    LOSE,
    DRAW
}

public abstract class Player {
    public abstract fun getMove(): Int
}

public final class ConsolePlayer(private val size: Int): Player() {

    public override fun getMove(): Int {
        return ConsoleInputWrapper.readInt(validator = { it in 0 until size })
    }
}

public final class ComputerPlayer(private val size: Int): Player() {

    public override fun getMove(): Int {
        return (0 until size).random()
    }
}

internal final class ConsoleInputWrapper {

    companion object {

        fun readString(prompt: String? = null, validator: ((String) -> Boolean)? = null): String {
            if (prompt != null) {
                println(prompt)
            }
            while (true) {
                print("> ")
                val input = readlnOrNull()?.trim()

                if (input.isNullOrBlank()) {
                    println("Invalid input")
                    continue
                }

                if (validator?.invoke(input) == false) {
                    println("Invalid input")
                    continue
                }

                return input
            }
        }

        fun readInt(prompt: String? = null, validator: ((Int) -> Boolean)? = null): Int {
            while (true) {
                val input = readString(prompt)
                val number = input.toIntOrNull()

                if (number == null) {
                    println("Invalid number")
                    continue
                }

                if (validator?.invoke(number) == false) {
                    println("Invalid number")
                    continue
                }

                return number
            }
        }
    }
}


fun main() {
    val moves = listOf("Rock", "Paper", "Scissors")
    val gameEngine = GameEngine(moves)
    val app = RockPaperScissors(gameEngine)

    println("Welcome to Rock-Paper-Scissors!")
    println("Choose game mode:")
    println("1: Player vs Player")
    println("2: Player vs Computer")

    val mode = ConsoleInputWrapper.readInt(validator = { it == 1 || it == 2 })

    when (mode) {
        1 -> {
            val player1 = ConsolePlayer(moves.size)
            val player2 = ConsolePlayer(moves.size)
            app.play(player1, player2)
        }
        2 -> {
            val player1 = ConsolePlayer(moves.size)
            val player2 = ComputerPlayer(moves.size)
            app.play(player1, player2)
        }
    }
}
